# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-07 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0003_auto_20190607_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='adresa',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
