# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-07 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('manufactDate', models.CharField(max_length=100)),
                ('available', models.PositiveIntegerField()),
                ('thumb', models.ImageField(blank=True, default='rio_img.png', upload_to=b'')),
            ],
        ),
    ]
